# This file is part of IntegerTriangles.
# Copyright Peter Luschny. License is MIT.

# Version of: UTC 2020-03-04 22:23:21
# 5ff91e80-5e5e-11ea-18f9-73ca7e94038a

# Do not edit this file, it is generated from the modules and will be overwritten!
# Edit the modules in the src directory and build this file with BuildTriangles.jl!

tstdir = realpath(joinpath(dirname(@__FILE__)))
srcdir = joinpath(dirname(tstdir), "src")
tstdir ∉ LOAD_PATH && push!(LOAD_PATH, tstdir)
srcdir ∉ LOAD_PATH && push!(LOAD_PATH, srcdir)
module perftests
using IntegerTriangles, Dates, InteractiveUtils
InteractiveUtils.versioninfo()
start = Dates.now()
# +++ Aliases.jl +++
# +++ SeqFingerPrint.jl +++
# +++ TrianglesBase.jl +++
# +++ TrianglesExamples.jl +++
# +++ TrianglesPlot.jl +++
# +++ TrianglesTraitCard.jl +++
# +++ TrianglesUtils.jl +++
stop = Dates.now()
tdiff = stop - start
println("\nJulia version: " * string(VERSION) )
println(start)
println("Total test time: ", tdiff)
end # module
