language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.6
  - nightly

jobs:
  allow_failures:
    - julia: nightly

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("IntegerTriangles"; coverage=true)'
