language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.6
  - nightly

jobs:
  allow_failures:
    - julia: nightly
  after_success: skip

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true
