language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - julia --color=yes -e 'using Pkg; Pkg.build()'
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
